version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db-medods
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass

    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/000001_create_users_table.up.sql:/docker-entrypoint-initdb.d/000001_create_users_table.up.sql
      - ./migrations/000002_add_users.up.sql:/docker-entrypoint-initdb.d/000002_add_users_up.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: docker
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: