version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      DB_HOST: db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/000001_create_users_table.up.sql:/docker-entrypoint-initdb.d/000001_create_users_table.up.sql
      - ./migrations/000002_add_users_table.up.sql:/docker-entrypoint-initdb.d/000002_add_users_table.up.sql
    networks:
      - medods-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: docker
      DB_USER: postgres
      DB_PASSWORD: mypass
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - medods-network
    restart: always

volumes:
  pgdata:

networks:
  medods-network:
    driver: bridge
