version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db-medods
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: